### ISSUE TITLE
Dealer should  check for Blackjack on 10,J,Q,K

### ISSUE THREAD

**Issue by kedoska** [kedoska/engine-blackjack#3]
### Rules

1. when Dealer's first card is any **10, J, Q or K** we should check for _BJ_
2. if Dealer has _BJ_, go to _showdown_

### Doubts

1. how you call this behavior / rule?
2. is this in any derived variants of the game or should be a configuration?

**Comment by gsdriver** [comment]
Most American casinos do check the hole card with a 10-value card showing; in Europe (European no-peek variant), the dealer doesn't check the hole card even with an Ace showing.  There should be a rules variant that doesn't check and go to showdown in this case.

I personally haven't seen a casino that doesn't check for a BJ with a 10 showing when they do check with an Ace showing - they either check the hole card in both cases or in neither case

**Comment by kedoska** [comment]
Yes, my only _problem_ with this "check" is that now the "environment" (miniserver in the example) must care about 2 things:

 1. hide the deck [here](https://github.com/kedoska/engine-blackjack/blob/master/examples/basicUI/miniserver.js#L37)
 2. and now _mask_ the second card of the dealer (after deal)

With that assumed, we can create a `no-peek` (on/off rule) that will do the magic during the _deal_.
`dealerHasBlackjack` is there... will use it.

**Comment by gsdriver** [comment]
Yeah, I'm looking at this and noticed that dealerCards only has one card after Deal, so there is no way to check.  I'm thinking of adding a new dealerHoleCard to the state so that the client can ignore it (could even mask this value from the client entirely until we transition to showdown), but we can still look at it internally if we peak

**Comment by kedoska** [comment]
https://github.com/kedoska/engine-blackjack/blob/master/src/game.js#L212

there... we probably should just pull the 2nd card.

the problem i was proposing (hide the second card) is actually "only related" to live environment but maybe we will have tester for RTP, or we just want to use this in a simulator to teach the player to play BJ.

I think we can assume that second card of the dealer must be mask after until showdown... in any case we do that for deck/s
