### ISSUE TITLE
How do I make a game with non-default parameters?

### ISSUE THREAD

**Issue by funcdoor** [kedoska/engine-blackjack#57]
I'm not sure what arguments to give to new Game() for things like standOnSoft17

**Comment by kedoska** [comment]
hi @funcdoor,

the `Game` cto needs 2 arguments:
1. the eventual initial state
2. the set of rules.

```javascript
constructor (initialState: State, rules: Rule = getRules({}))
```

Assuming the default settings returned by [the function `getRules()`](https://github.com/kedoska/engine-blackjack/blob/master/src/presets.js#L34) is not what you want for your players, you can override the rules like this:

```javascript
const { presets, actions, Game } = require('engine-blackjack')

const overrideRules = {
  decks: 6
}

const rules = presets.getRules(overrideRules)

const game = new Game(null, rules)

const stateAfterDeal = game.dispatch(actions.deal({ bet: 100 }))

console.dir(stateAfterDeal)
```

**Comment by funcdoor** [comment]
Thanks very much, I got it working! I actually wanted to turn off "standOnSoft17"; I've found that "hit on soft 17" is the norm in Las Vegas tables.
