### ISSUE TITLE
Suggestion: 5, 6, and 7-card Charlie

### ISSUE THREAD

**Issue by funcdoor** [kedoska/engine-blackjack#58]
An optional rule exists where a player's hand will automatically win if they reach a certain number of cards _without busting_ usually called "5 Card Charlie" to "7 Card Charlie" (depending on the variation). I believe this variant is common enough that it would be nice to have as an option

source: https://wizardofodds.com/games/blackjack/strategy/charlie/

**Comment by kedoska** [comment]
It does not looks very difficult. Could be implemented [here](https://github.com/kedoska/engine-blackjack/blob/master/src/game.js#L312) and [here](https://github.com/kedoska/engine-blackjack/blob/master/src/game.js#L321) by passing an extra value to the `getHandInfoAfter...`.

I will search for more statistics and eventually will look into it on the weekend to prepare some tests.
