### ISSUE TITLE
Implement strategy

### ISSUE THREAD

**Issue by kedoska** [kedoska/engine-blackjack#7]
I really like both, the project of @gsdriver [blackjack-strategy](https://github.com/gsdriver/blackjack-strategy) and the references of [wizardofodds](http://wizardofodds.com/games/blackjack/strategy/calculator/) used by him in README  .

Instead of rebuild the entire strategy rules, I'm going to add the first dependencies even if i told in README we do not want to do it. That project is absolutely correlated to this project so I can talk with my ego and explain it.

There are some things to align in the rule of the engine but it is possible.
### Strategy as a Mode

Strategy will be integrated as a post-action, player will receive the list of `good` actions so that the UI can easily handle the alert when player is doing something wrong (without calling the server again)
### What about the Licence ?

No idea yet, as it will be probably integrated as dependencies, I will add references in source code where the lib is actually.

**Comment by gsdriver** [comment]
Thanks - yeah I think blackjack-strategy could be useful for a learning-style blackjack mode.  I added the idea of "strategyComplexity" exactly with this use case in mind.  The "advanced" strategy is meant to exactly match wizardofodds, but I also want a "simple" strategy that people who are just learning the game can follow and more easily remember.  Alerting the user when they deviate makes sense - that way whether they are a beginner or mode advanced player they can still learn from the system.
